apiVersion: apps/v1
kind: Deployment
metadata:
  name: mac-app-v2-deployment
  labels:
    app: mac-app-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mac-app-v2
  template:
    metadata:
      labels:
        app: mac-app-v2
    spec:
      containers:
        - name: mac-app-v2-container
          image: httpd:latest
          ports:
            - containerPort: 80
