apiVersion: apps/v1
kind: Deployment
metadata:
  name: mac-app-v1-deployment
  labels:
    app: mac-app-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mac-app-v1
  template:
    metadata:
      labels:
        app: mac-app-v1
    spec:
      containers:
        - name: mac-app-v1-container
          image: nginx:latest
          ports:
            - containerPort: 80
