apiVersion: v1
kind: Service
metadata:
  name: mac-service
spec:
  type: NodePort
  selector:
    # mac-app-v1 or mac-app-v2
    app: mac-app-v2
  ports:
    - protocol: TCP
      port: 80 # Port of service
      targetPort: 80 # Port of Pod
      nodePort: 30001 # Port of Node
      # Node -> Service -> Pod
      